### ISSUE TITLE
Error message in console + right click retrieval not working

### ISSUE THREAD

**Issue by paddymadge** [apavarino/Deadchest#34] opened 2021-12-17 23:06 UTC
**Context**
- Plugin name
DeadChest
- Plugin version
4.8.0
- Minecraft version
1.18.1
- Server type (Bukkit/Spigot/Paper...)
Paper (build 68)

**Describe the bug**
Sends a error to console "Could not pass event PlayerInteractEvent to DeadChest v4.8.0"
&
Can't right click to retrieve DeadChest 

**To Reproduce**
1. Install the plugin
2. Die with stuff in your inventory
3. Try to retrieve it / look at console

**Expected behavior**
Being able to retrieve it with right click, and no error messages in console.

**Comment by apavarino** [comment] 2021-12-18 12:07
Error on the console fixed on version 4.8.1.

Right clicking mode is disable since 4.8.0. It's not a bug. 👍

**Closed by apavarino** 2021-12-18 12:07 UTC
Labels: bug

**Comment by paddymadge** [comment] 2021-12-18 12:29
Oops. Didn't read changelog. Only thing I can say is that I and others love what you made here, hope you keep going with the plugin! :)

**Comment by apavarino** [comment] 2021-12-18 15:57
Thanks a lot !
