### ISSUE TITLE
Decent Holograms support for the holograms bug

### ISSUE THREAD

**Issue by Rectos28** [apavarino/Deadchest#41] opened 2022-04-18 18:31 UTC
Is your feature request related to a problem? 
As all knows about the holograms bug that they stay on the world even removing the plugin or removing the deadchest and the fix for the bug is annoying as I have to teleport to each bugged chest and remove the holograms one by one.

Describe the solution you'd like:
By using holograms plugin as a dependency such as [Decent Holograms](https://www.spigotmc.org/resources/decent-holograms-1-8-1-18-2-papi-support-no-dependencies.96927/) we can eleminate the bug using there api to make the holograms and removing them.

**Comment by broken1arrow** [comment] 2022-04-21 12:49
I don´t know how that will solve the issue. Because it is much deeper problem some cause this (he have added some fixes for this). 
You can read about it here, spigot have done a "fix" (not good fix for it but a fix).
https://github.com/PaperMC/Paper/issues/5872

**Comment by Rectos28** [comment] 2022-04-21 15:27
From what I understand how the holograms is used in this plugin is that being as a vanilla entity. Using the holograms plugin as dependency will let the plugin handels everything from loading, unloding and deleting the holograms. Which will help fixing the issue.

**Comment by broken1arrow** [comment] 2022-04-21 20:19
> From what I understand how the holograms is used in this plugin is that being as a vanilla entity. Using the holograms plugin as dependency will let the plugin handels everything from loading, unloding and deleting the holograms. Which will help fixing the issue.

The issue is when try remove from unloaded chunks. I think only way is show the holos client side to remove the issue completely (don't know if Decent Holograms have this option).

**Comment by apavarino** [comment] 2022-11-22 20:47
Fixed on last version

**Closed by apavarino** 2022-11-22 20:47 UTC
Labels: enhancement
