### ISSUE TITLE
Deadchest's dont unload.

### ISSUE THREAD

**Issue by captainion2119** [apavarino/Deadchest#20] opened 2021-09-07 16:13 UTC
**Been running an SMP since a while now, but I have noticed many ghost deadchests just stuck in the world.**
- Deadchest 
- 4.7.0 (latest on bukkit as of now)
- 1.17.1
- Paper 1.17.1

**Description**
There are random deadchest timers (without any chest) floating around in the Whole Minecraft world, loaded/unloaded chucks both. According to the players the timers have exceeded the time limit prior to this observation.

**To Reproduce**
No steps recorded as of now but will update if found.

**Expected behavior**
The deadchest timers should delete themselves once the Chest runs out of time

**Screenshots**
![2021-09-07_21 36 21](https://user-images.githubusercontent.com/35457553/132377564-dda75f08-830a-4e20-97a3-0ae97ed7005b.png)

**Comment by PrideIsLife** [comment] 2021-09-16 17:12
I encountered exactly the same issue.
see image below : 

![image](https://user-images.githubusercontent.com/82092021/133655812-c13427fb-1504-4c7b-82be-ee4900257614.png)

**Comment by fabegalo** [comment] 2021-10-02 23:24
I'm suffering like same problem, is there any solution to remove all?

**Comment by captainion2119** [comment] 2021-10-03 15:31
To everyone facing the same problem, I joined the discord server of apavarino, 
He has mentioned only 2 methods of solving this problem in the server they are:

using the command "/dc repair" (inbuilt command made for fixing errors such as the ghost deadchests)

or if this doesn't work (As it didn't for me) using the following minecraft command "/minecraft:kill @e[sort=nearest,limit=1,type=minecraft:armor_stand]" to kill the invisible armour stands also works, but requires to be used continuously to kill every "deadchest of (Username)" and "00h 00m 002 Left" separately.

**Comment by fabegalo** [comment] 2021-10-03 15:57
> A todos que enfrentam o mesmo problema, entrei no discord server do apavarino, ele citou apenas 2 métodos de resolver este problema no servidor são eles:
> 
> usando o comando "/ dc repair" (comando embutido feito para corrigir erros, como os deadchests fantasmas)
> 
> ou se isso não funcionar (como não funcionou para mim) usando o seguinte comando do minecraft "/ minecraft: kill @e [sort = mais próximo, limite = 1, type = minecraft: armor_stand]" para matar os suportes de armadura invisíveis também funciona, mas precisa ser usado continuamente para matar todos os "baús mortos de (nome de usuário)" e "00h 00m 00s restantes" separadamente.

Wouldn't this command delete the players' stand weapons as well?

**Comment by Deeptanil** [comment] 2021-10-04 02:30
This doesn't solve the problem though. The devs said they are looking into it.

**To reproduce**
Happens when the player has an inventory and keeps dying over and over.

This is what a player on my server reported to me.

**Comment by captainion2119** [comment] 2021-11-08 08:27
ah, alright. I just switched to a different grave plugin cuz, well it was looking bad, having so many ghost deadchests.

But I am sure interested in how they will go forward in fixing this bug

**Comment by apavarino** [comment] 2021-11-11 16:43
Hi everyone.

This issue is caused by an issue in Paper for version **1.17.1**. it's not directly related to Deadchest (https://github.com/PaperMC/Paper/issues/5872)

On deadchest, the bug occured when a timer of deadchest is out and the chunk is currently unload. In this case due to the bug, deadchest is not able to retrieve the armor stand and can't remove it

I have two option. Make major change on plugin to get ride of this or wait until Paper fix that bug.

I think i will do the first option. I will keep your informed here.

Thanks all for your feedback.

**Comment by captainion2119** [comment] 2021-11-11 16:48
I had suspected that, but shrugged it off when it became common, thank you for responding, hoping to see a fix soon!
👍

**Comment by apavarino** [comment] 2021-11-30 23:33
Hi guys,
Good news ! After hours of work I finally found a workaround for this issue.

I need to test it better but the result are very good !

I will release a new version soon with this fix and some other stuff.

Thanks for your patience.

**Comment by apavarino** [comment] 2021-12-03 21:40
Fixed on 4.8.0

**Closed by apavarino** 2021-12-03 21:40 UTC
Labels: bug

**Comment by Deeptanil** [comment] 2021-12-04 19:06
> Fixed on 4.8.0

And where's that version?

**Comment by apavarino** [comment] 2021-12-05 10:19
Currently under validation by the bukkit staff. That's should arrive in the next 24h.
