### ISSUE TITLE
PlayerHeads are not Safe!

### ISSUE THREAD

**Issue by PaBox** [apavarino/Deadchest#19] opened 2021-09-07 15:34 UTC
**Context**
- DeadChest
- 4.7.0
- 1.16.5
- PaperMC

**Describe the bug**
It is possible to destroy the corresponding player head (chest type 2), without being the owner.

**To Reproduce**
1. /kill yourself
2. go to location of the chest
3. Use a water bucket to place a water source block in the block, where the player head is located.
4. The playerhead and all items will drop.

**Expected behavior**
The playerhead should be immediatly replaced - no matter if it was done by the owner or by another player.

P.S. You also did not change the duration of existence of a single chest, but rather increased the amount of possible chests at the same time.

Hope that I could help,
Greetings.

**Comment by captainion2119** [comment] 2021-09-09 11:41
yeah the mods on my server reported that, well, using drop item type 1 (chest) for now.

**Comment by apavarino** [comment] 2021-11-11 14:26
I'm currently not able to reproduce. Can you provide a list of plugin you are using ?

**Comment by PaBox** [comment] 2021-11-14 19:29
I am still able to reproduce this on paper on the named version, without any other plugins on a virtual server. Be sure to place the bucket in the same block as the player head is. I havent yet looked at any updated version after that. Sadly have been using chests since september.

**Comment by apavarino** [comment] 2021-12-03 20:41
Thanks for the report ! Successfully reproduce. This issue will be fixed on the next plugin version.

**Comment by apavarino** [comment] 2021-12-03 21:39
Fixed on 4.8.0

**Closed by apavarino** 2021-12-03 21:39 UTC
Labels: bug
